### ISSUE TITLE
Adding an image with a title does not load the image any more

### ISSUE THREAD

**Issue by santilland** [spectrachrome/vuetify-scrollytelling#27]
It seems that if a title is define in the custom dashboard for an image, the title is appended to the used image url in the scrolly story and thus the image no longer loads

**Comment by spectrachrome** [comment]
Closing this issue as the code responsible for this issue lives in eodash.

**Comment by spectrachrome** [comment]
Closing this issue as the code responsible for this issue lives in eodash.
